/** @type {import('tailwindcss').Config} */
// Sprint A1: extracted verbatim from the former inline Play-CDN config in index.html
// so the locally built CSS is pixel-identical to the CDN output.
// .cjs extension: the package is "type": "module", Tailwind 3.4 loads CJS configs reliably.
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "coal-bg": "#1F1D1B",
        "on-secondary-fixed": "#1c1c19",
        "tertiary-fixed-dim": "#5ddac8",
        "secondary-container": "#474743",
        "on-primary": "#5d1901",
        "tertiary-fixed": "#7cf7e4",
        "outline-variant": "#55433d",
        "primary": "#ffb59d",
        "inverse-on-surface": "#32302e",
        "warn-yellow": "#F3AE35",
        "error-container": "#93000a",
        "on-tertiary-container": "#00312c",
        "secondary-fixed": "#e5e2dd",
        "primary-container": "#da7756",
        "inverse-surface": "#e7e1de",
        "border-muted": "#2E2C29",
        "on-tertiary-fixed-variant": "#005048",
        "surface": "#151311",
        "background": "#151311",
        "tertiary": "#5ddac8",
        "error": "#ffb4ab",
        "on-background": "#e7e1de",
        "primary-fixed-dim": "#ffb59d",
        "primary-fixed": "#ffdbd0",
        "secondary": "#c9c6c2",
        "on-secondary": "#31302d",
        "outline": "#a38c85",
        "on-primary-fixed": "#390b00",
        "on-tertiary": "#003731",
        "on-surface": "#e7e1de",
        "surface-tint": "#ffb59d",
        "cream-text": "#F5F2ED",
        "inverse-primary": "#994528",
        "surface-dim": "#151311",
        "on-secondary-container": "#b7b5b0",
        "on-secondary-fixed-variant": "#474743",
        "clay-accent": "#DA7756",
        "surface-variant": "#373432",
        "on-tertiary-fixed": "#00201c",
        "secondary-fixed-dim": "#c9c6c2",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#541500",
        "on-error": "#690005",
        "surface-container-high": "#2c2a27",
        "on-surface-variant": "#dbc1b9",
        "surface-container": "#211f1d",
        "surface-container-lowest": "#100e0c",
        "surface-container-highest": "#373432",
        "tertiary-container": "#00a494",
        "on-primary-fixed-variant": "#7b2f13",
        "coal-surface": "#141413",
        "surface-container-low": "#1d1b19",
        "surface-bright": "#3b3936",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        gutter: "16px",
        "stack-md": "16px",
        unit: "4px",
        "margin-desktop": "32px",
        "stack-lg": "24px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Thmanyah Serif Display"],
        "body-md": ["Thmanyah Sans"],
        "body-lg": ["Thmanyah Sans"],
        "headline-xl": ["Thmanyah Serif Display"],
        "label-md": ["Thmanyah Sans"],
        "label-sm": ["Thmanyah Sans"],
        "headline-lg": ["Thmanyah Serif Display"],
        "mono-code": ["monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "headline-xl": ["36px", { lineHeight: "1.2", fontWeight: "900" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "mono-code": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
